### ISSUE TITLE
Typescript types do not work on undefined as first parameter

### ISSUE THREAD

**Issue by macalinao** [facebookincubator/idx#67]
The following does not work:

```
          const myVar: { a: { b: string } } | null = null as {
            a: { b: string };
          } | null;
          const something = idx(myVar, _ => _.a.b);
```

**Comment by macalinao** [comment]
This should have no compile errors, but it does.

The error is `[ts] Object is possibly 'null'. [2531]`.

**Comment by Horaddrim** [comment]
If you are using the `{ strict: true }` option in your `tsconfig.json`, it will always check about possible `null` values, and for `never` values too, so, if you want to compile your code, you can disable that, or do a check in this variable, because the `idx` type definition returns a possible `null` in this [line](https://github.com/facebookincubator/idx/blob/482879c3d7c524412649e00d71a687edcf6b84d1/packages/idx/src/idx.d.ts#L70) :D 
Checking the return here `const something = idx(myVar, _ => _.a.b);` with something like -> `const something = idx(myVar, _ => _.a.b) || 'Error message here'; ` will solve the problem.

**Comment by yungsters** [comment]
Thanks, @Horaddrim.

Sounds like this question has been resolved.

**Comment by macalinao** [comment]
@Horaddrim This doesn't solve the problem for me.

```
    const myVar: { a: { b: string } } | null = null as {
      a: { b: string };
    } | null;
    const something = idx(myVar, _ => _.a.b) || "TEST";
```

still fails the build.
